### ISSUE TITLE
Crash when exiting after being started from hbl

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#110]
When libtransistor NROs are started from hbl, they crash on exit, yielding error 2347-0026. This is an undocumented errno. Pinging @plutooo on this. Any hints as to what that error code means ?

**Comment by roblabla** [comment]
Apparently, test_helloworld doesn't crash. But test_display crashes.

**Comment by roblabla** [comment]
Apparently : Failed to unmap code memory (.data+.bss).

**Comment by misson20000** [comment]
I was like 90% sure I fixed this. My guess before doing any further investigation is that some resources might take a while to release before they reset memory states.

**Comment by roblabla** [comment]
Appears to be fixed in latest Libtransistor. For further mitigations, see #111
