### ISSUE TITLE
Changes in headers not detected

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#112]
I've noticed a lot of crashes happen because people update libtransistor and run `make` without first cleaning their previous build. I suppose this is because our makefile don't detect changes in headers. It should. It is possible to ask gcc/clang to generate "header dependencies" through the -MM flag. See https://stackoverflow.com/questions/2394609/makefile-header-dependencies

**Comment by misson20000** [comment]
We already do this, but probably not very well.
