### ISSUE TITLE
Implement dlopen/dlsym

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#117]
Necessary to allow dynamically loading cores in RetroArch. It should be possible to do, by loading the NROs, relocating them, and then using the dynamic section to find the symbols. However, libtransistor does not (AFAIK) generate a valid dynamic section (that's why you can't load them with the IDA loader).

**Comment by misson20000** [comment]
This will also be useful for traNVparency. We should add a result code to HBABI to indicate that an NRO is "not executable"

**Comment by misson20000** [comment]
closed with #143
