### ISSUE TITLE
Malloc locking for newlib

### ISSUE THREAD

**Issue by misson20000** [reswitched/libtransistor#12]

**Comment by roblabla** [comment]
Can you describe what this means @misson20000 ?

**Comment by misson20000** [comment]
Implementing locks to protect malloc and such against multithreaded access. I don't remember whether this is a separate issue or not, but we should also do reentrancy properly soon.

**Comment by misson20000** [comment]
fixed in 0dfd1ea3e2898ecf3261a0d05d6a5e85cb23fb2f
