### ISSUE TITLE
make failing on mkdir -p build/lib

### ISSUE THREAD

**Issue by curtisy1** [reswitched/libtransistor#13]
So yeah, just running ```make``` somehow doesn't work for me. I get the following error:
```
make
mkdir -p build/lib
llvm-mc -arch=aarch64 -triple aarch64-none-switch lib/crt0.nro.S -filetype=obj -o build/lib/crt0.nro.o
llvm-mc: error: invalid target 'aarch64'.
make: *** [Makefile:47: build/lib/crt0.nro.o] Error 1
```

I'm running Solus Budgie (Linux) and all dependencies are installed properly. I also tried removing the ```aarch64-none-switch``` that was added in order to fix building on Mac, but that didn't do the trick unfortunately.

If you have any ideas on how to fix this, I'd be grateful.

Thanks!

**Comment by misson20000** [comment]
Looks like your llvm wasn't compiled with aarch64 support. I'm not familiar with Mac. @SomeoneWeird, any insight?

**Comment by curtisy1** [comment]
Alright, I'll try and recompile llvm from source tomorrow (although I'm
sure it should work as Unicorn and Mephisto both compiled just fine).

Just to avoid confusion, I'm not using a Mac but a Linux machine (probably
a pretty uncommon distro though). I just thought the patch provided by
vgmoose could have been the cause but that wasn't it.

misson20000 <notifications@github.com> schrieb am So., 5. Nov. 2017, 02:08:

**Comment by misson20000** [comment]
Unicorn and Mephisto were both compiled targeting x86(_64), but libtransistor targets aarch64. Are you running some kind of minimalist distribution that would've disabled all llvm targets except x86(_64)?

**Comment by curtisy1** [comment]
Are you running some kind of minimalist distribution that would've disabled all LLVM targets except x86(_64)?
It's not minimalist, but they indeed disabled all but the hosts architecture in llvm. I'm building from source right now, so it should hopefully be just fine afterwards.

Thanks for your help, it's much appreciated.
