### ISSUE TITLE
SIP Issue Mac OSX High Sierra 

### ISSUE THREAD

**Issue by natehaxx** [reswitched/libtransistor#134]
SDL2 Cant be Build under usr/bin since Mac OSX El Captian there is a SIP Protection which wont Allow any kind of Installation.

it needs to be build now under usr/local.

**Comment by misson20000** [comment]
error logs please

**Comment by natehaxx** [comment]
MacbookPro:libtransistor DJAlexDaCosta$ make
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make -C ./build//sdl2/
/bin/sh /Users/DJAlexDaCosta/libtransistor/sdl2/build-scripts/updaterev.sh
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make -C ./build//sdl2/ install
/bin/sh /Users/DJAlexDaCosta/libtransistor/sdl2/build-scripts/updaterev.sh
/bin/sh /Users/DJAlexDaCosta/libtransistor/sdl2/build-scripts/mkinstalldirs /bin
/usr/bin/install -c -m 755 sdl2-config /bin/sdl2-config
Error (SIP Enabled) 

https://www.infoworld.com/article/2988096/mac-os-x/sorry-unix-fans-os-x-el-capitan-kills-root.html

**Comment by misson20000** [comment]
unset `LIBTRANSISTOR_HOME`
