### ISSUE TITLE
zlib issue , unable to run Zipfiles on the Switch

### ISSUE THREAD

**Issue by natehaxx** [reswitched/libtransistor#137]
i cant get an crash log from the switch besides 2168-0002 

Emulator: Mame2003 
Issue: Loading Zip Files turn into instant Crash , loading Zipfiles with Yuzu or Ryujinx works fine.

i am not the only person having trouble with zip on HW

**Comment by misson20000** [comment]
This does not look like a libtransistor issue. I would suspect uninitialized memory
