### ISSUE TITLE
Undefined symbols when compiling on archlinux

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#16]
So I'm compiling this from an archlinux box on which I installed `clang`, `llvm`, `lld` and the python deps. I'm currently stuck with the following error : 

```
ld.lld -Bsymbolic --shared --emit-relocs --no-gc-sections --no-undefined -T link.T -o build/test/test_malloc.nro.s        o build/test/test_malloc.o --whole-archive build/lib/libtransistor.nro.a --no-whole-archive newlib/aarch64-none-sw        itch/newlib/libc.a
ld.lld: error: undefined symbol: __stack_chk_guard
>>> referenced by ipc.c:53 (lib/ipc.c:53)
>>>               ipc.o:(ipc_marshal) in archive build/lib/libtransistor.nro.a
```

Full output : https://gist.github.com/5af916a59ce82bc73aabe91bf14eeaf7

**Comment by misson20000** [comment]
That's definitely something I've seen before. What version of clang are you using?

**Comment by Pokemod97** [comment]
Default arch llvm/clang. Solution was Just put -fno-stack-protector in CC_FLAGS in the libtransistor Makefile same as it was in the beginning

**Comment by misson20000** [comment]
Alright. Mind submitting a PR for that?
This is the version I'm running on Arch (installed clang-svn from the AUR):
```
$ clang --version
clang version 6.0.0 (trunk 311507)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
