### ISSUE TITLE
libtransistor may accidentally use host headers

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#22]
Currently, libtransistor doesn't pass the `-nostdinc` flag to clang when compiling, which causes it to use the host's headers. When I tried to add `-nostdinc`, I was greeted with errors about the use of stdbool.h, which isn't defined by newlib.

Here's the current flags I use to make clang happy : 

```
        .clang_arg("-nostdinc")
        .clang_args(&["-isystem", "/usr/lib/clang/5.0.0/include"])
        .clang_args(&["-isystem", "libtransistor/newlib/newlib/libc/include"])
        .clang_args(&["-isystem", "libtransistor/newlib/newlib/libc/sys/switch/include"])
        .clang_arg("-Ilibtransistor/include")
```

`/usr/lib/clang/CLANG_VERSION/include` contains stdbool.h, among other headers, defining many built-in C types. The equivalent in GCC seems to be `/usr/lib/gcc/TARGET_TRIPLET/GCC_VERSION/include`.

**Comment by valpackett** [comment]
How was this solved? I'm getting a `stdbool.h` not found from `libtransistor/types.h`:

https://github.com/reswitched/libtransistor/blob/b5123e9517a8ad85c7c7a46e1de670372e06db78/include/libtransistor/types.h#L15-L17

These headers are not in the libtransistor-base release...

**Comment by valpackett** [comment]
So I had to get the files from a Linux box, because FreeBSD always uses the system ones since clang is the default compiler.

```bash
scp archlinux-box.lan:/usr/lib/clang/6.0.0/include/stdnoreturn.h dist/include
scp archlinux-box.lan:/usr/lib/clang/6.0.0/include/stdbool.h dist/include
scp archlinux-box.lan:/usr/lib/clang/6.0.0/include/stddef.h dist/include
scp archlinux-box.lan:/usr/lib/clang/6.0.0/include/stdarg.h dist/include
```

And edit `dist/include/limits.h` to disable the `!defined __GNUC__ || __GNUC__ < 2` check and the `include_next`.

Now everything works.

```bash
gmake LLVM_POSTFIX=60
yuzu build/test/test_display.nro
```

**Comment by misson20000** [comment]
I believe this was solved by using -nostdlibinc, which removes standard library headers but leaves compiler headers

**Comment by valpackett** [comment]
Yeah, but these "compiler headers" seem to only be available on Linux...
