### ISSUE TITLE
Clang incorrectly assumes mfloat-abi=soft

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#38]
With the merge of a recent PR (I think the makefile one), I started seeing the following warning everywhere : 

```
clang-5.0: warning: unknown platform, assuming -mfloat-abi=soft
```

As far as I know, the nintendo switch (more specifically, the tegra x1) supports hard floats. We should pass `-mfloat-abi=hard` to the Makefile ?

**Comment by dvdfreitag** [comment]
Ok, so this is odd. [According to arm](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0774b/chr1417451577871.html),

> The` -mfloat-abi` option is not valid with ARMv8 AArch64 targets. AArch64 targets use hardware floating-point instructions and hardware floating-point linkage. However, you can prevent the use of floating-point instructions or floating-point registers for AArch64 targets with the `-mcpu=name+nofp+nosimd` option. Subsequent use of floating-point data types in this mode is unsupported.

Out of curiosity, what does `file` report for the output files that produce this warning? The `CFLAGS` properly sets to tune for `cortex-a53` and the target is `aarch64`, so it should not be producing `float-abi` warnings.

For reference, `file` should print something like:
> ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), with debug_info, not stripped

If this is some Arch issue, I would suggest adding `-march=armv8-a+simd+fp` and see if that removes your warnings.

**Comment by misson20000** [comment]
I'm unable to reproduce with clang 6.
```
$ clang --version
clang version 6.0.0 (trunk 311507)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Compiling clang 5 right now to test...

**Comment by dvdfreitag** [comment]
Running clang 5, can't reproduce either.

> $ clang-5.0 --version
clang version 5.0.0-3 (tags/RELEASE_500/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by roblabla** [comment]
I think this is linked to https://github.com/reswitched/libtransistor/pull/39
