### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#41]
There currently is no license associated with libtransistor, which makes it default to All rights reserved. It seems `libnx` is using ISC (basically "everyone can do whatever"). Should we follow suit ?

**Comment by SomeoneWeird** [comment]
All our other projects are ISC (minus Mephisto, which is GPL because of the GDB stub) so I'm +1

**Comment by SciresM** [comment]
Definitely ISC, please.

**Comment by dvdfreitag** [comment]
Thirded on ISC
