### ISSUE TITLE
crt0.nro.S error

### ISSUE THREAD

**Issue by Dwood15** [reswitched/libtransistor#43]
```
~/libtransistor# make
mkdir -p /root/libtransistor/build/lib
llvm-mc -arch=aarch64 -triple aarch64-none-switch /root/libtransistor/lib/crt0.nro.S -filetype=obj -o /root/libtransistor/build/lib/crt0.nro.o
/root/libtransistor/lib/crt0.nro.S:42:21: error: expected compatible register, symbol or integer in range [0, 4095]
        sub sp, sp, 0x10
```

Ubuntu trusty, Just installed llvm, clang, cmake, python-lz4, etc.

**Comment by dvdfreitag** [comment]
What version of llvm-mc are you using? I believe 5.0 or higher is required.

**Comment by Dwood15** [comment]
I'm on 3.x, upgrading Trusty to Xenial, then going to see if/what that fixes. My cmake was hopelessly out of date as well.

**Comment by roblabla** [comment]
you'll need llvm5 from the llvm repos https://apt.llvm.org/

**Comment by Dwood15** [comment]
Upgrading to 16.04 didn't do anything, just got done installing llvm5, running make now.

**Comment by dvdfreitag** [comment]
You will likely also need to run make like so `make LLVM_POSTFIX=-5.0` because clang 5 installs like `/usr/bin/clang-5.0`, otherwise it will attempt to use the 3.8 toolchain.

**Comment by Dwood15** [comment]
I got the library to compile.
