### ISSUE TITLE
Failed to get IP: nifm_init returned e401

### ISSUE THREAD

**Issue by Dwood15** [reswitched/libtransistor#53]
[somethings' failing to find an ip address](https://pastebin.com/CweTs3zj) after I load my switch with runnro ace.nro in pegaswitch. (latest libtransistor + pegaswitch, all tools up to date)

**Comment by roblabla** [comment]
This is not technically necessary, if you know your switch IP already.

There's probably *something* wrong [in there](https://github.com/reswitched/libtransistor/blob/master/lib/ipc/nifm.c). You can compare the impl to the docs [there](http://switchbrew.org/index.php?title=Network_Interface_services).

I'm kinda busy with pthread right now, I'll get to this when I get that sorted.

**Comment by misson20000** [comment]
fixed in fe84b052248190901b3b8d70e8dff7ec2696f8aa
