### ISSUE TITLE
Document ace_loader usage

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#55]
Right now, ace_loader's readme is a bit barren. We should probably explain how it works, and how to use it, as it's likely to become the main way to use homebrew.

**Comment by misson20000** [comment]
We should also make better API docs for libtransistor. Does anyone want to set up Doxygen and have Travis push to GitHub Pages or something?

**Comment by roblabla** [comment]
@3Daniel expressed interest in setting up Doxygen btw.

**Comment by roblabla** [comment]
removing good first issue as this is solely about ace_loader, whose docs should be written by one of us. I have a bit of on an outline on ReswitchedWeekly's Development Setup guide. We could probably just copy paste most of it in ace_loader's readme.

For the doxygen, look at #77

**Comment by seanp2500** [comment]
so i have my http server up but pegaswitched switch does not load icons/nros.  I can see server if i open local host is there a certain port or way of issuing command to host ftp server is using nodejs ftp server?
