### ISSUE TITLE
Virtual filesystem

### ISSUE THREAD

**Issue by misson20000** [reswitched/libtransistor#58]
In trying to load resources for an application, one will quickly encounter the problem of no filesystem functions having been implemented.

I'd like to implement a sort of virtual filesystem API, where you can mount filesystems provided by various modules and access files from there. Filesystem providers could include some sort of network filesystem, a read-only filesystem embedded in the binary, one that lives in memory, or, eventually, native filesystems such as the console's internal storage and SD card.

Thoughts? What exactly do we want this to look like?

**Comment by misson20000** [comment]
I think that in order to maintain best compatibility when porting applications from other platforms, paths should look like they do on Linux: a single root filesystem with other filesystems mounted to directories within that root filesystem. I would want to have that root filesystem be either a ready-only one embedded within the binary, or one that lives in memory, so directories can be created underneath it for use as mount points. I'm leaning towards the read-only embedded option, so that it will be easier to get simple applications up and running quickly. We could also have it be writeable and just store written changes in memory to be discarded when the application exits.

**Comment by misson20000** [comment]
An embedded filesystem would probably look like Makefile rules to build some sort of archive and then convert it to an object file that will be linked with the rest of the binary. The filesystem module will contain weak symbols for a default, empty filesystem.

**Comment by roblabla** [comment]
So, we should probably be a bit careful to make sure we stay compatible with the switch. From what I understand, the switch has multiple "disjointed" filesystems (which basically are objects implementing [IFileSystem service](http://switchbrew.org/index.php?title=Filesystem_services#IFileSystem)), and doesn't present a unified view of them all. So this actually makes our jobs fairly easy : we could have our own abstraction layer fairly easily. *but*, to make our life as easy as possible, we should retain compatibility with path syntax, for instance.

So thinking about this, we could present a hierarchy of mounts like the linux kernel does. Basically have something like 

```
struct filesystem_ops {
    int (*open)(void *arg, char *path);
    int (*read)(void *arg, int fd);
    int (*write)(void *arg, int fd);
    // ...
}
```

We'd provide a default filesystem that just keeps everything in RAM as the root filesystem (that's what Linux does by default ^^). People would be able to call `libtransistor_mount(const char *path, struct filesystem_ops *ops);` to mount said filesystem in a certain path. The idea being that you could later call

```
ifilesystem_t switchsavefs = fs_mount_save_data(); // Open SaveData FS through switch IPC
struct filesystem_ops *savefs = fs_create_switch_fs(switchsavefs);
libtransistor_mount("/save", savefs);
char *tar; // Some TAR archive or something.
struct filesystem_ops *archivefs = fs_create_archive_fs(tar);
libtransistor_mount("/data", archivefs);
```

And have the switch's Save FileSystem mounted to `/save` and a tarball statically linked in your program mounted in `/data`. (Dunno if a tarball makes sense, probably super inefficient, just trying to illustrate my point. Might want to look at linux's squashfs for an existing read-only, embedded filesystem).

**Comment by misson20000** [comment]
Yeah, that's pretty much what I was thinking.

**Comment by roblabla** [comment]
According to motezazer, we can read and write to save files from the browser on the Switch. Furthermore, saves have no space limitations. We should investigate this, but it might make our lives a lot simpler than I thought !

**Comment by maci0** [comment]
Was wondering about how much of physfs can be re-used for the VFS functionality....

**Comment by misson20000** [comment]
This is what I've got so far for the filesystem abstraction layer: https://github.com/misson20000/libtransistor/blob/f9c7804befe3cd3a2f2ba4a692a9e74b84b0478e/include/libtransistor/fs/inode.h

I'm not sure whether to make mountpoints be handled by matching paths in `trn_fs_open` or by filesystem drivers keeping associations between their inodes and mountpoints.

**Comment by roblabla** [comment]
FS Drivers shouldn't care about their mountpoint, they should all act as if they're the "root" IMO. What should happen is when you do `open`, it should first figure out what filesystem is involved, and call the FS' `open` hook with the root truncated from the path.

E.G.

```
mount("/mnt", somemnt)
open("/mnt/test") // Call somemnt.open("/test")
```

**Comment by misson20000** [comment]
Yeah, I'm just a little worried about the implementation of figuring out what filesystem is involved. It's seeming to me like if we can't ask the filesystem driver to associate information with an inode for us, we'd have to keep a map of mountpoint paths to filesystem roots and compare paths.

**Comment by misson20000** [comment]
Or maybe we could maintain a map of `(fs, inode number) mountpoint -> (trn_inode_t) root` instead of `(char[PATH_LEN+1]) mountpoint -> (trn_inode_t) root`

**Comment by roblabla** [comment]
So I have an easier plan as a first pass towards this: have `/` be fully virtual, and mounts be direct descendants to it. So you can mount sdcardfs as `/sd`, squashfs as `/squash`, but you can't nest mounts, and `/` is "immutable".

I'll work on this this week.

**Comment by roblabla** [comment]
Done with the merge of sdcard support.
