### ISSUE TITLE
Filesize Issue with Nros

### ISSUE THREAD

**Issue by Mafiacoding** [reswitched/libtransistor#87]
Here is my Log building an Nro bigger than 20 MB , the issue dont happen with smaller files up to 16Mega. 

Switch Crashes with Error Code: 2168-0003 (cant also load the file with Yuzu)

- NRO 42614784B (42614784B) bss 19767296B
- NRO base at 0x000000321576C000
- found suitable block at 0x58b8c00000, size 0x1ed000
- found suitable block at 0x58b90ed000, size 0xc2000
- found suitable block at 0x58b992f000, size 0x6d4000
- found suitable block at 0x58ba007000, size 0x8000
- found suitable block at 0x58ba02e000, size 0xd2000
- found suitable block at 0x58ba1c0000, size 0x44000
- found suitable block at 0x58ba362000, size 0x71f000
- found suitable block at 0x58baa82000, size 0x1000
- found suitable block at 0x58babda000, size 0x1000
- found suitable block at 0x58bac4a000, size 0x1000
- found suitable block at 0x58bb3d4000, size 0x1000
- found suitable block at 0x58bb3eb000, size 0x1000
- found suitable block at 0x58bb45a000, size 0x1000
- found suitable block at 0x58bb45c000, size 0x1000
- found suitable block at 0x58bb4b5000, size 0x1000
- found suitable block at 0x58bb4bf000, size 0x1000
- found suitable block at 0x58bcca4000, size 0x1000
- splitting this block around our overridden heap...
- overridden heap @ 0x58c0376000, size 0xzx
- block before: 0x58bccbc000, 0x36ba000
- block after: 0x58c0776000, 0x3452000
- found suitable block at 0x58c827f000, size 0x8981000
- mapped 275083264B contiguous memory block
- writing NRO config
```

**Comment by roblabla** [comment]
I believe this was actually a retroarch bug. This should have fixed it https://github.com/libretro/RetroArch/commit/bb1fdad0d983adc96de337a05546ed9eb99911ed

If I'm wrong, please reopen.
