### ISSUE TITLE
OverrideHeap should contain "real" heap

### ISSUE THREAD

**Issue by roblabla** [reswitched/libtransistor#95]
Right now, ace_loader sends "remapped" heap in the OverrideHeap loader section. This is bad for multiple reasons:

1. We end up needing hacks to get "real" Heap, that is necessary for some syscalls (See #69)
2. Libnx expects real heap there.

We should either find a way to properly unmap the whole browser, or settle with finding the biggest contiguous region in our heap.

**Comment by misson20000** [comment]
I'm planning on using the biggest region, then also passing an alloc_pages key. The alloc_pages key will have a function pointer that should be called if it is recognized which will add the region used for OverrideHeap back to the memory pool for alloc_pages
