### ISSUE TITLE
NXODance/Linking is Fragile

### ISSUE THREAD

**Issue by misson20000** [reswitched/libtransistor#98]
I would really appreciate the input of someone who's better at linker wrangling than I am on how to get the linker to just put everything into three sections. The current nxodance solution is really stupid. We pretty much manually concatenate sections from the ELF file into the RX, R, and RW sections that wind up in the NRO. The particularly fragile part is that we try to predict where each section goes based off of its size and a hardcoded alignment, which breaks when the linker does things like adding a section that we don't expect in the middle of everything.

**Comment by roblabla** [comment]
Alright got a fun one: The `log_string` function would segfault for seemingly no reason. Debugging in Mephisto, I see this, *before anything even ran* (that is, PC is on the first instruction of start):

```
(gdb) p log_length
$1 = 4107284145303677259
(gdb) p &log_length
$6 = (size_t *) 0x71000007b0 <tohex+32>
(gdb) display/10i tohex
3: x/10i tohex
   0x7100000790 <tohex>:        cmp     x1, #0x1
   0x7100000794 <tohex+4>:      b.lt    0x71000007ec <tohex+92>  // b.tstop
   0x7100000798 <tohex+8>:      adrp    x10, 0x7100040000
   0x710000079c <tohex+12>:     add     x8, x0, x1
   0x71000007a0 <tohex+16>:     mov     x9, x2
   0x71000007a4 <tohex+20>:     add     x10, x10, #0x230
   0x71000007a8 <tohex+24>:     ldrb    w11, [x0]
   0x71000007ac <tohex+28>:     lsr     x11, x11, #4
   0x71000007b0 <tohex+32>:     ldrb    w11, [x10, x11]
   0x71000007b4 <tohex+36>:     strb    w11, [x9]
```

Somehow, the linker thought it'd be a good idea to put the log_string variable (which is supposed to be in the BSS) right in the middle of my text segment, in a function. I suspect this to be again a case of "elf2nxo sucks".

https://github.com/roblabla/libtransistor/commit/93b06255f1929515c2f243c9d5c69e9f99474723 the test_fs_stress causes this for me.
